### PR TITLE
feat: storage password hash

### PR DESCRIPTION
**Pull request by WindSpiritSR**
Signed-off-by: WindSpirit <simon343riley@gmail.com>

### CODE REVIEW

**Comment by WindSpiritSR** [comment]
Deployed at https://forum.leviatan.cn/

**Comment by hsluoyz** [comment]
@WindSpiritSR no need to change this now. Finally we will move to Casdoor: https://github.com/casbin/casnode/issues/145

**Comment by hsluoyz** [comment]
It's a good practice to send issue first before making a new PR.

**Comment by WindSpiritSR** [comment]
copy that ~

**Pull request closed without merging**
