### PR TITLE
Fix zmage broken

### PR DESCRIPTION
**Pull request by MayankMittal1**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MayankMittal1 which code line does the fix?

**Comment by MayankMittal1** [comment]
@hsluoyz the code which does the fixes is in yarn lock
Some redundant package was removed that was causing the issue

**Comment by hsluoyz** [comment]
@MayankMittal1 

1. Then don't change other files. Only modify the lock. The other changes make people confused.
2. Is this the same as I delete the lock file and re-generate it? Did you manually edit it?

**Comment by MayankMittal1** [comment]
@hsluoyz yes just have to regenerate it

**Comment by MayankMittal1** [comment]
@hsluoyz merge please

**Comment by Nekotoxin** [comment]
> @hsluoyz merge please

If there are some redundant package ,I think that modify the package.json to remove them will be better.
Once other users run yarn install，the old lock file will be overwritten.
I find it was because a bug in zmage version 8.5 beta37,so roll back to beta36 in package.json

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/452

**Pull request closed without merging**
