### PR TITLE
fix: all codemirror focus area

### LINKED ISSUE #239: Cannot focus textbox from the bottom
Post: https://forum.casbin.com/new/casbin

image

Similar to reply: https://forum.casbin.com/t/146

image

### PR DESCRIPTION
**Pull request by WindSpiritSR**
fix #239 

Deployed at https://forum.leviatan.cn/

Signed-off-by: WindSpirit <simon343riley@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@kocoler @Kininaru plz review.

**Review by keainye — APPROVED** [review]

**Comment by hsluoyz** [comment]
@WindSpiritSR 

1. Which places are fixed?
2. Provide a demo link

**Comment by WindSpiritSR** [comment]
Fixed places:
1. https://forum.leviatan.cn/admin/node/edit/1001 - Description
2. https://forum.leviatan.cn/edit/topic/1 - Content
3. https://forum.leviatan.cn/new - Content
4. https://forum.leviatan.cn/go/1001 - Content
5. https://forum.leviatan.cn/t/1 - Reply

Create `short`、`middle`、`long` and `unresizable` style for CodeMirror.

And I found that the width of the title edit box(`<textarea>`) is resizable and can wrap, should I continue to push a PR here or submit a new issue?

**Comment by hsluoyz** [comment]
> And I found that the width of the title edit box(<textarea>) is resizable and can wrap, should I continue to push a PR here or submit a new issue?

I think it's acceptable.

**Pull request merged**
