### PR TITLE
feat: added night mode

### LINKED ISSUE #163: Dark mode is not working
Dark mode is not working on clicking the toggle button beside the profile image

https://user-images.githubusercontent.com/42040782/111624460-bc4e4600-8811-11eb-9096-8e74553fbfdd.mp4

### PR DESCRIPTION
**Pull request by keainye**
fix: https://github.com/casbin/casbin-forum/issues/163

Code in my branch has been deployed at https://forum-hk.chromium.link/

Login, then you can try dark theme.

### CODE REVIEW

**Comment by keainye** [comment]
You can only login via GitHub, because I didn't set an email server or a SMS service.

**Comment by keainye** [comment]
Code deployed on my server have some differences from the repo. Since css on jsdeliver haven't been updated yet, I'm using the css file stored on my server.

**Comment by kunalprakash1309** [comment]
On enabling dark mode search bar is not visible. And complete page reload again

**Comment by keainye** [comment]
@kunalprakash1309 Thanks for reviewing, working on this

**Comment by kunalprakash1309** [comment]
Actually I am also working on this. @Kininaru

**Pull request merged**
