### PR TITLE
feat: add note book

### PR DESCRIPTION
**Pull request by oranges-eating**
Signed-off-by: killer <1533063601@qq.com>
demo:http://20.196.193.233:7000/
user_1/123

Fix: https://github.com/casbin/casnode/issues/341

### CODE REVIEW

**Comment by hsluoyz** [comment]
@oranges-eating demo link?

**Comment by oranges-eating** [comment]
> @oranges-eating demo link?

already add

**Comment by hsluoyz** [comment]
@oranges-eating why I input more, the height become smaller? I think this is a bug

image

**Comment by oranges-eating** [comment]
> @oranges-eating why I input more, the height become smaller? I think this is a bug
> 
> image

yes,already fixed

**Comment by hsluoyz** [comment]
@oranges-eating can you implement the same UI as v2? https://v2ex.com/notes

v2:

image

Ours:

image

**Comment by oranges-eating** [comment]
Sorry, I'm not good at front-end

**Comment by hsluoyz** [comment]
@kocoler plz review

**Comment by kocoler** [comment]
There are some problems:
1. UI is much different from v2, basically all pages are different.
2. It lacks some functions, such as URL setting (this pr is based on id, the problem is not very serious), the right of file number bar is missing, and the brief introduction of the folder. The most important thing is that the content of the file looks like just `plaintext`, and we should at least implement markdown and rich text like posting.

**Comment by oranges-eating** [comment]
@kocoler 
already add markdown and rich text

**Comment by hsluoyz** [comment]
@oranges-eating demo link?

**Comment by oranges-eating** [comment]
> @oranges-eating demo link?

The link has not changed, the same as before

**Comment by hsluoyz** [comment]
@kocoler plz review

**Comment by kocoler** [comment]
In fact, there are still many problems, most of which are UI problems.
Like: 
image

image

image

If these are all fixed, then this pr could be merged as a new feature.

Or could it be merged in advance, and then these problems can be fixed in the new pr?

**Comment by hsluoyz** [comment]
Closed for low quality.

**Pull request closed without merging**
