### PR TITLE
refactor: put all frontend configurations into one config file

### LINKED ISSUE #325: Put all frontend configurations into one config file
Like logo, forum name, forum description, etc. All these things should be easily configurable in one place, like inside a single config file in the frontend project (/web).

image

image

### PR DESCRIPTION
**Pull request by oranges-eating**
Fix: https://github.com/casbin/casnode/issues/325
Signed-off-by: killer <1533063601@qq.com>

### CODE REVIEW

**Comment by oranges-eating** [comment]
@hsluoyz @Kininaru  plz review

**Comment by hsluoyz** [comment]
@kocoler @Kininaru plz review

**Comment by WindSpiritSR** [comment]
@oranges-eating Did you forget to remove `background-image`

https://github.com/casbin/casnode/blob/fc8a0634e5777bf6e7605fa7008bc48e47aa61d5/web/src/App.css#L4-L31

**Comment by oranges-eating** [comment]
> @oranges-eating Did you forget to remove `background-image`
> 
> https://github.com/casbin/casnode/blob/fc8a0634e5777bf6e7605fa7008bc48e47aa61d5/web/src/App.css#L4-L31

I know,but the priority of styles in js is higher than css, I think there is no harm in keeping it

**Comment by oranges-eating** [comment]
@Kininaru @kocoler plz review

**Comment by hsluoyz** [comment]
@oranges-eating demo link

**Pull request merged**
