### PR TITLE
feat: add react lazyload

### LINKED ISSUE #314: No LazyLoad  for prod build package. All script conbine to a big chunk.js
No LazyLoad  for prod build package. All script conbine to a big chunk.js 

Maybe use lazyload can pick up index page load speed. 

```js
import LazyLoad from "./lazyload";

export default class MainLayout extends Component {
    render() {
        return (
            <div className="main">
                <Switch>
                    <Route path="/" exact render={() => (<Redirect to="/guide" />)} />
                    <Route path="/guide" component={LazyLoad(()=>import("./guide"))}></Route>
                    <Route path="/login" component={LazyLoad(()=>import("./login"))}></Route>
                    <Route path="/search" component={LazyLoad(()=>import("./search"))} />
                    <Route path="/main" component={LazyLoad(()=>import("./main"))} />
                    <Route path="/scan" component={LazyLoad(()=>import("./scan"))} />
                    {/* 不存在 */}
                    <Route render={() => (<Redirect to="/guide" />)}></Route>
                </Switch>
            </div>
        )
    }
}
```

### PR DESCRIPTION
**Pull request by keainye**
Resolved: https://github.com/casbin/casnode/issues/314

Main pages will loaded lazily.

Users can modify `web/src/components/LazyLoad.js renderFallback()` to change loading style.

### CODE REVIEW

**Comment by keainye** [comment]
@hsluoyz @cyg0618 plz review.

**Comment by keainye** [comment]
Lazy loaded js files.

https://user-images.githubusercontent.com/42638489/125163733-1314cc80-e1c1-11eb-8513-9d1db37d2137.mp4

**Comment by hsluoyz** [comment]
@Kininaru demo link? Will it be OK if we put the npm built files into CDN?

**Comment by keainye** [comment]
@hsluoyz 
Demo link: https://forum.chromium.link

**Pull request merged**
