### PR TITLE
feat: click the button to directly sign in in the comment plugin mode

### LINKED ISSUE #382: Click the button to directly sign in in the comment plugin mode
Casnode supports to be used as a comment plugin for other sites like: https://oa.casbin.com/

When the user is not signed in, we will show a button as follows. We want the user to click the button to directly sign in.

image

### PR DESCRIPTION
**Pull request by seriouszyx**
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

Fix: https://github.com/casbin/casnode/issues/382

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx demo link?

**Comment by hsluoyz** [comment]
@seriouszyx the effect is wrong. We want to let the outsite page to sign in, not the iframe to sign in. So you first need to send message from iframe to the outside page via methods like postMessage: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage , then let the outside page trigger signing in process.

**Comment by seriouszyx** [comment]
> @seriouszyx the effect is wrong. We want to let the outsite page to sign in, not the iframe to sign in. So you first need to send message from iframe to the outside page via methods like postMessage: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage , then let the outside page trigger signing in process.

I implemented the effect you said locallly but encountered another problem. Even if OA is logged in, the comment plugin still queries the login status of Casnode. If not, the button is still displayed. 

image

**Comment by hsluoyz** [comment]
@seriouszyx that should not happen. Maybe some random commit broke it. Can you also fix this bug too?

**Comment by seriouszyx** [comment]
@hsluoyz I found that [get-account API](https://github.com/casbin/casnode/blob/dd869376737a89ce169425f5b7495f3c978e8064/controllers/account.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L99) need to login and then get account based on accessToken. In comment plugin mode, is it necessary to login casnode first? If not, what should we do? Provide another API which is allowed to get account without login?

**Comment by hsluoyz** [comment]
@seriouszyx it already works now.

https://github.com/casbin/casnode/commit/33d747856e38250c1f425eed01d14f150e0d2ce7

https://github.com/casbin/casbin-oa/commit/fbbf234e18be96ca7e99d830925dcfb171ce188b

**Pull request closed without merging**
