### PR TITLE
fix: zoom image broken

### LINKED ISSUE #436: The picture zoom-in based on react-zmage is broken
We use: https://github.com/Caldis/react-zmage to perform the image zoom-in. But we have found a bug now, see: https://forum.casbin.com/t/589

When we click on a picture with this icon, the picture should be zoomed in, but now it will be broken with all white

image

image

### PR DESCRIPTION
**Pull request by MayankMittal1**
fix: #436 
CPT2203060120-500x563
The package Zmage seemed to be broken, replaced the places which require zoom images with package https://www.npmjs.com/package/react-image-zooom

### CODE REVIEW

**Comment by hsluoyz** [comment]
@MayankMittal1 can we fix the Zmage ? I think Zmage still looks better

**Comment by Nekotoxin** [comment]
> fix: #436 CPT2203060120-500x563 The package Zmage seemed to be broken, replaced the places which require zoom images with package https://www.npmjs.com/package/react-image-zooom

would you like to continue work on this?

**Comment by MayankMittal1** [comment]
@Nekotoxin I've tried everything but zmage is just not working, now I'm searching for alternatives which are at par with zmage ui

**Comment by Nekotoxin** [comment]
> @Nekotoxin I've tried everything but zmage is just not working, now I'm searching for alternatives which are at par with zmage ui

good luck to you 😂

**Comment by hsluoyz** [comment]
@MayankMittal1 @Nekotoxin the original zoom-in once worked pretty well (at least when adding it). There must be one commit that breaks it. We need to locate this commit and find out how to mitigate.

For how to locate the "bad" commit, you can use binary-search between the commit adding this feature and the latest HEAD commit. It will take O(n) times of attempts.

**Comment by MayankMittal1** [comment]
@hsluoyz yes it must have worked I've tried making demo apps to test it it just works fine
Can you recall at what time you last remember it worked so that i can cycle commits and check what broke it

**Comment by hsluoyz** [comment]
@MayankMittal1 I don't know. See:

```
For how to locate the "bad" commit, you can use binary-search between the commit adding this feature and the latest HEAD commit. It will take O(n) times of attempts.
```

**Comment by MayankMittal1** [comment]
Ok will do

**Pull request closed without merging**
