### PR TITLE
fix: codemirror textarea focus area

### PR DESCRIPTION
**Pull request by WindSpiritSR**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@WindSpiritSR fix:

image

**Comment by hsluoyz** [comment]
@WindSpiritSR can you provide a demo site?

**Comment by WindSpiritSR** [comment]
Sorry, that's a wrong pr

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/casnode/pull/241

**Pull request closed without merging**
