### PR TITLE
feat: add topic and account swagger api docs

### LINKED ISSUE #278: Provide our Go backend API docs (via Swagger) in the forum header
See how we did it in Casdoor, it will be similar: https://github.com/casbin/casdoor/issues/31

Casdoor's Swagger docs is online here: https://door.casbin.com/swagger/

image

In Casnode, we will add it here:

image

### PR DESCRIPTION
**Pull request by sh1luo**
Fix: https://github.com/casbin/casnode/issues/278

Signed-off-by: wasabi <690898835@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@sh1luo online demo link

**Review by keainye — APPROVED** [review]
Changes look fine. Please provide a demo.

**Comment by hsluoyz** [comment]
@sh1luo Swagger doesn't show when logged in, plz fix it

image

**Comment by sh1luo** [comment]
> @sh1luo Swagger doesn't show when logged in, plz fix it
> 
> image

ok

**Pull request merged**
