### PR TITLE
fix: fix duplicatedly publishing and databases error

### LINKED ISSUE #398: There seems to be a bug when creating a new topic.
There seems to be a bug. When creating a new topic, clicking multiple times will create multiple identical topics.
Normally, only one should be created.

image

### PR DESCRIPTION
**Pull request by Nekotoxin**
fix: #398

### CODE REVIEW

**Comment by MayankMittal1** [comment]
@Nekotoxin as @hsluoyz mentioned we have to make an index on the topic field for faster access?
you seemed to have removed that

**Comment by Nekotoxin** [comment]
> @Nekotoxin as @hsluoyz mentioned we have to make an index on the topic field for faster access? you seemed to have removed that
}V13~1S~Y ~_3(UW6O 92%J

(PA))X@HDHLL20TD5(9~V{7
It seems that the index will cause an error in mysql v8.0.27,so remove it temporarily

**Comment by Nekotoxin** [comment]
> @Nekotoxin as @hsluoyz mentioned we have to make an index on the topic field for faster access? you seemed to have removed that

.

**Comment by MayankMittal1** [comment]
@Nekotoxin i searched about it, yes composite index is giving an error, still we need an index on topic field for fast performance,
added in #439

**Pull request merged**
