### PR TITLE
fix: create a null user when select language

### PR DESCRIPTION
**Pull request by WindSpiritSR**
Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

### CODE REVIEW

**Comment by oranges-eating** [comment]
the pr is already merged
https://github.com/casbin/casnode/pull/292

**Comment by WindSpiritSR** [comment]
@oranges-eating At #292, if user not login, backend will return a null user info with language like:

```json
{
    "user": "",
    "avater": "",
    "language": "en",
    ...
}
```

The front end will think that this is a logged in user.

**Comment by WindSpiritSR** [comment]
He merged too fast, I didn’t have time to add this commit to the right PR Σ( ° △ °|||)︴

**Comment by hsluoyz** [comment]
But there's still bug after merging: https://github.com/casbin/casnode/pull/292

How to reproduce:


https://user-images.githubusercontent.com/3787410/122521217-23fd7280-d047-11eb-9d6f-86ac0f96f3a1.mp4

**Comment by WindSpiritSR** [comment]
@hsluoyz This PR solved this problem
Deployed at: https://forum.leviatan.cn/

**Pull request merged**
