### PR TITLE
fix: Return to the previous page after language selection

### PR DESCRIPTION
**Pull request by oranges-eating**
fix: #297 
demo:http://www.killerwing.xyz:7000/
Signed-off-by: killer <1533063601@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@kocoler @Kininaru plz review

**Comment by kocoler** [comment]
I don't recommend using `history.back();`, because this may cause redirect to another domain's websites, or other uncertain 
 issues.
Such as the user visiting this page directly, then this page will simply go back to the previous location.
It is hard to manage website history, so I recommend just using query(?redirect=) to redirect. Other website are using the same method as well.

**Comment by hsluoyz** [comment]
@kocoler good point!

@oranges-eating plz fix.

**Comment by hsluoyz** [comment]
@oranges-eating merged now. Plz fix this comment: https://github.com/casbin/casnode/pull/299#issuecomment-864488843 in next PR.

**Comment by hsluoyz** [comment]
@oranges-eating this PR doesn't work for logged-in user.

**Comment by hsluoyz** [comment]
@oranges-eating @kocoler I'm already tired of testing your PRs on this topic any more. Plz make a final PR to fix **ALL** conditions.

1. Logged-in
2. Not logged-in

**Comment by oranges-eating** [comment]
Is it possible to provide server logs, because I cannot reproduce this problem locally and on my own deployed server.

**Comment by hsluoyz** [comment]
@oranges-eating see video:

https://user-images.githubusercontent.com/3787410/122755175-308ffe00-d2c7-11eb-8a6b-d94721fae69b.mp4

**Comment by oranges-eating** [comment]
> @oranges-eating看视频：
> 
>  QQ.20210621192954.mp4

I know this, click to switch language, api/update-member-language returns 200, but the account information has not been changed, I want to check the backend log, why the account information is not changed

**Pull request merged**
