### PR TITLE
chore: optimize images

### PR DESCRIPTION
**Pull request by rajpratik71**
*Total -- 43.74kb -> 27.72kb (36.63%)

/web/src/logo.png -- 33.46kb -> 18.87kb (43.62%)
/web/public/favicon.png -- 10.28kb -> 8.85kb (13.88%)

Signed-off-by: ImgBotApp <ImgBotHelp@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Rajpratik71 can you share why you did this change?

**Comment by rajpratik71** [comment]
> @Rajpratik71 can you share why you did this change?

this is to optimize/reduce image size

**Comment by hsluoyz** [comment]
It seems too trivial. Are you using Casnode? Saving 10KB doesn't give you anything valuable actually.

**Comment by rajpratik71** [comment]
Recently started exploring casbin and casdoor. Just added the PR, opened by Bot for optimization. 

In long term, for thousand or millions of requests, it will give something.

**Comment by hsluoyz** [comment]
@Rajpratik71 fix:

image

**Comment by rajpratik71** [comment]
> @Rajpratik71 fix:
> 
> image

Already done but it is not taking it 

image

**Comment by rajpratik71** [comment]
Leave it. 
Thanks

**Pull request closed without merging**
