### PR TITLE
fix: codemirror textarea focus area

### PR DESCRIPTION
**Pull request by WindSpiritSR**
Signed-off-by: WindSpirit <simon343riley@gmail.com>

### CODE REVIEW

**Comment by WindSpiritSR** [comment]
the demo site is on deploying

**Comment by keainye** [comment]
It does seem to focus correctly now, but input area become too high.

image

Origin: 
image

**Comment by hsluoyz** [comment]
@WindSpiritSR plz keep the original height.

**Comment by WindSpiritSR** [comment]
Not found a perfect solution to this problem yet. But I think we can make it work better first.

1. Set `height: 100% !important` to `.CodeMirror`
2. Remove `height` or `min-height` from CodeMirror's father content
3. Add blank lines to the CodeMirror's value when it mount

**Comment by WindSpiritSR** [comment]
Deployed at https://forum.leviatan.cn/

**Comment by hsluoyz** [comment]
@WindSpiritSR the cursor also needs fix.

**Comment by hsluoyz** [comment]
@kocoler @Kininaru plz review.

**Review by kocoler — APPROVED** [review]

**Review by keainye — APPROVED** [review]

**Pull request merged**
