### PR TITLE
feat: Install Casnode by BT panel

### PR DESCRIPTION
**Pull request by oranges-eating**
Signed-off-by: killer <1533063601@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@oranges-eating I suggesting putting this docs to: https://casnode.org/docs/ . There will only be a single root README.md in this repo. You can add a pointer in the MD to point to the official site.

**Review by keainye — COMMENTED** [review]
These steps are too difficult for a normal user. I suggest that we can compile some binaries for mainly used Linux distributions then make it possible to download in BT store. 

Maybe we can also compile binaries for Windows and macOS.

**Comment by kocoler** [comment]
> These steps are too difficult for a normal user. I suggest that we can compile some binaries for mainly used Linux distributions then make it possible to download in BT store.
> 
> Maybe we can also compile binaries for Windows and macOS.

I think using docker is more effective and more transplantable? 
After all the BT panel is representative of a production environment. Maybe it's time to complete issue #133 .

**Comment by keainye** [comment]
> > These steps are too difficult for a normal user. I suggest that we can compile some binaries for mainly used Linux distributions then make it possible to download in BT store.
> > Maybe we can also compile binaries for Windows and macOS.
> 
> I think using docker is more effective and more transplantable?
> After all the BT panel is representative of a production environment. Maybe it's time to complete issue #133 .

Sounds great, it is more convenient to use docker.

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casnode/casnode-website/pull/17

**Pull request closed without merging**
