### PR TITLE
fix: notification bug

### LINKED ISSUE #184: The "Unread" notifications are still labeled as unread, even if the user has checked the message
See: https://forum.casbin.com/t/107

### PR DESCRIPTION
**Pull request by keainye**
fix: https://github.com/casbin/casbin-forum/issues/184

New: now, unread notifications will update automatically without refreshing the page.

Deployed at: https://forum-hk.chromium.link/

### CODE REVIEW

**Comment by hsluoyz** [comment]
@kocoler please review.

**Comment by kocoler** [comment]
I found that you use the polling method to make new message reminders more timely, but this approach will bring more pressure to the server-side. Now, polling with congestion or using WebSocket provides a more reliable service, but both of these need some time to achieve, and they have some shortcomings(such as more overhead) as well.
So maybe we could take a turn on polling message reminder as a **configuration**? And make the time interval as a configurable variable at the same time.

**Comment by keainye** [comment]
@kocoler 

Got that. I will add these to web config this afternoon.

**Comment by keainye** [comment]
@kocoler Added `EnableNotificationAutoUpdate` and `NotificationAutoUpdatePeriod` to Conf.js, please review.

**Review by kocoler — APPROVED** [review]
LGTM

**Comment by hsluoyz** [comment]
@Kininaru well done!

**Pull request merged**
